name: hs-all-in-one
version: "0.1"
github:  "nomeata/hs-all-in-one"
license: MIT
author:  "Joachim Breitner"
maintainer: "mail@joachim-breitner.de"
#copyright:  "2023 Your Name"

extra-source-files:
- ChangeLog.md

synopsis: Merges multiple Haskell modules into one


dependencies:
  - base >=4.9 && <4.10
  - haskell-src-exts
  - haskell-names
  - syb
  - hashable

library:
 source-dirs: .

executables:
  hs-all-in-one-exe:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-all-in-one