

#ghc 8.0.1
resolver: lts-7.24

packages: 
  - .

# Using stack 2.5.1 - had troubles using 2.15.1 and 3.3.1
# AFAIK there's no way to specify the stack version itself in these files 
# I strongly advise using ghcup to set stack to 2.5.1
extra-deps: 
 - haskell-src-exts-1.18.0
 - haskell-names-0.8.0
 - syb-0.7.2.4
 - hashable-1.2.7.0
 